### ISSUE TITLE
Publish plugin ?

### ISSUE THREAD

**Issue by senare** [glesys/terraform-provider-glesys#8]
Would it be possible to have this available as community plugin, mark it as BETA ? 

https://www.terraform.io/docs/providers/type/community-index.html

**Comment by norrland** [comment]
I'll make a note to look into this.

**Comment by senare** [comment]
Great thanks !

**Comment by norrland** [comment]
This has been a private project of mine in order to learn how to code in Golang. I cannot promise any frequent updates to this.
But will try to at least test and comment any contributions to the code.

**Comment by rawtaz** [comment]
I agree, can't we get this published so that one can just use it in the TF code without having to clone the repo and build the plugin manually?

I mailed Glesys a couple of weeks ago and asked if this plugin was fine to use in production, and the answer was yes, so with that I figure why not just go ahead and publish it? Nothing is ever perfect, it can be updated and any bugs fixed even when it's published.

**Comment by norrland** [comment]
Fixed in v0.4.2
